import { User } from './user-list.models';

export const userListMockData: User[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'Vb2QK@example.com',
    phone: '1234567890',
    address: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zip: '12345',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'K0yfI@example.com',
    phone: '9876543210',
    address: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zip: '67890',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    email: 'K0yfI@example.com',
    phone: '9876543210',
    address: '789 Oak St',
    city: 'Sometown',
    state: 'TX',
    zip: '54321',
  },
  {
    id: 4,
    name: 'Alice Brown',
    email: 'K0yfI@example.com',
    phone: '9876543210',
    address: '321 Pine St',
    city: 'Hometown',
    state: 'FL',
    zip: '98765',
  },
  {
    id: 5,
    name: 'Charlie Davis',
    email: 'K0yfI@example.com',
    phone: '9876543210',
    address: '654 Cedar St',
    city: 'Villagetown',
    state: 'IL',
    zip: '54321',
  },
];
